"""PersistentPoker-Bench public package."""

from persistentpoker_bench.budget import BudgetCaps, BudgetExceededError, BudgetTracker
from persistentpoker_bench.cards import Card, Suit, cards_to_notation, parse_cards, standard_deck
from persistentpoker_bench.game_state import (
    Action,
    ActionType,
    HandState,
    PlayerState,
    Street,
    TableConfig,
    create_hand_state,
)
from persistentpoker_bench.hand_evaluator import EvaluatedHand, evaluate_hand, evaluate_notation
from persistentpoker_bench.hand_runner import (
    DecisionEnvelope,
    HandObserver,
    HandRunResult,
    HandRunnerConfig,
    StaticDecisionAgent,
    run_seeded_hand,
)
from persistentpoker_bench.interactive import (
    HumanCommand,
    HumanDecisionAgent,
    PassiveBotAgent,
    PlaySeatKind,
    PlaySeatSpec,
    PlaySessionConfig,
    TerminalHandObserver,
    parse_play_session_config,
    parse_human_command,
    play_terminal_match,
    run_play_session,
)
from persistentpoker_bench.leaderboard import LeaderboardRow, build_leaderboard_rows, export_leaderboard_csv
from persistentpoker_bench.local_models import LocalModelConfig, create_local_backend
from persistentpoker_bench.live_play import LiveMatchController
from persistentpoker_bench.memory_check import MemoryCheckResult, evaluate_memory
from persistentpoker_bench.match_runner import MatchRunResult, MatchRunnerConfig, flatten_match_transcript, run_seeded_match
from persistentpoker_bench.metrics import AggregateMetrics, compute_match_metrics
from persistentpoker_bench.model_registry import (
    DEFAULT_MODEL_REGISTRY,
    EFFICIENCY_MODELS,
    FRONTIER_MODELS,
    LeaderboardTrack,
    RegisteredModel,
    find_registered_model,
    models_for_track,
)
from persistentpoker_bench.models import DEFAULT_MODEL_PRIORITY, ModelTarget
from persistentpoker_bench.parsing import ParsedDecision, parse_llm_decision
from persistentpoker_bench.pool import PersistentPool
from persistentpoker_bench.prompting import PromptBundle, build_decision_prompt
from persistentpoker_bench.replay import (
    build_match_replay,
    export_match_replay_json,
    render_replay_hand_markdown,
    render_replay_summary_markdown,
    serialize_hand_replay,
)
from persistentpoker_bench.retries import RetryPolicy
from persistentpoker_bench.runtime_agents import (
    LiteLLMRuntimeAgent,
    LocalModelRuntimeAgent,
    RuntimeDecisionEnvelope,
    runtime_envelope_to_dict,
)
from persistentpoker_bench.schemas import (
    LLMDecision,
    WinnerPoolDecision,
    decision_example_payload,
    decision_json_schema,
    normalize_decision_payload,
)
from persistentpoker_bench.serialization import serialize_hand_state, serialize_legal_actions
from persistentpoker_bench.showdown import PotAllocation, ShowdownResult, resolve_showdown
from persistentpoker_bench.spec import (
    DEFAULT_BIG_BLIND,
    DEFAULT_DETERMINISTIC_SEED,
    DEFAULT_PLAYER_COUNT,
    DEFAULT_SMALL_BLIND,
    DEFAULT_STARTING_STACK,
    MAX_PLAYER_COUNT,
    MIN_PLAYER_COUNT,
    HandCategory,
    ProjectSpec,
    get_project_spec,
)
from persistentpoker_bench.tiebreak import D6TieBreaker, DiceTieBreakResult, serialize_tiebreak_result
from persistentpoker_bench.tournament import (
    MatchRecord,
    TournamentEntrant,
    TournamentLineup,
    TournamentResult,
    TournamentRunnerConfig,
    export_decision_traces_jsonl,
    export_match_results_jsonl,
    export_match_summaries_jsonl,
    flatten_tournament_match_transcript,
    run_tournament,
    serialize_match_record,
)
from persistentpoker_bench.web_ui import build_web_app
from persistentpoker_bench.video_renderer import render_video_from_source

__all__ = [
    "Action",
    "ActionType",
    "BudgetCaps",
    "BudgetExceededError",
    "BudgetTracker",
    "Card",
    "DEFAULT_BIG_BLIND",
    "DEFAULT_DETERMINISTIC_SEED",
    "DEFAULT_MODEL_REGISTRY",
    "DEFAULT_MODEL_PRIORITY",
    "DEFAULT_PLAYER_COUNT",
    "DEFAULT_SMALL_BLIND",
    "DEFAULT_STARTING_STACK",
    "DecisionEnvelope",
    "D6TieBreaker",
    "DiceTieBreakResult",
    "EFFICIENCY_MODELS",
    "EvaluatedHand",
    "FRONTIER_MODELS",
    "HandObserver",
    "LiteLLMRuntimeAgent",
    "LocalModelConfig",
    "LocalModelRuntimeAgent",
    "LeaderboardRow",
    "MatchRunResult",
    "MatchRunnerConfig",
    "MatchRecord",
    "HandRunResult",
    "HandRunnerConfig",
    "HandState",
    "HandCategory",
    "HumanCommand",
    "HumanDecisionAgent",
    "LLMDecision",
    "LeaderboardTrack",
    "LiveMatchController",
    "MAX_PLAYER_COUNT",
    "MemoryCheckResult",
    "MIN_PLAYER_COUNT",
    "ModelTarget",
    "ParsedDecision",
    "PlayerState",
    "PotAllocation",
    "PersistentPool",
    "PassiveBotAgent",
    "PlaySeatKind",
    "PlaySeatSpec",
    "PlaySessionConfig",
    "PromptBundle",
    "ProjectSpec",
    "RegisteredModel",
    "RetryPolicy",
    "RuntimeDecisionEnvelope",
    "ShowdownResult",
    "StaticDecisionAgent",
    "Street",
    "Suit",
    "TableConfig",
    "TerminalHandObserver",
    "TournamentEntrant",
    "TournamentLineup",
    "TournamentResult",
    "TournamentRunnerConfig",
    "WinnerPoolDecision",
    "build_decision_prompt",
    "build_leaderboard_rows",
    "cards_to_notation",
    "create_hand_state",
    "create_local_backend",
    "decision_example_payload",
    "decision_json_schema",
    "evaluate_hand",
    "evaluate_memory",
    "evaluate_notation",
    "export_match_replay_json",
    "export_decision_traces_jsonl",
    "export_leaderboard_csv",
    "export_match_results_jsonl",
    "export_match_summaries_jsonl",
    "find_registered_model",
    "flatten_match_transcript",
    "flatten_tournament_match_transcript",
    "get_project_spec",
    "models_for_track",
    "normalize_decision_payload",
    "parse_llm_decision",
    "parse_cards",
    "parse_play_session_config",
    "parse_human_command",
    "compute_match_metrics",
    "resolve_showdown",
    "run_seeded_hand",
    "run_seeded_match",
    "run_tournament",
    "runtime_envelope_to_dict",
    "run_play_session",
    "serialize_tiebreak_result",
    "serialize_match_record",
    "serialize_hand_state",
    "serialize_legal_actions",
    "serialize_hand_replay",
    "render_replay_hand_markdown",
    "render_replay_summary_markdown",
    "build_match_replay",
    "build_web_app",
    "render_video_from_source",
    "play_terminal_match",
    "standard_deck",
    "AggregateMetrics",
]
